services:
  - type: web
    name: kb-chat
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://kb-chat-jqdk.onrender.com
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AI_PROVIDER
        value: mock
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 947604684664-sbjfl0jmj332b81fmqeu7dd3tsct94l2.apps.googleusercontent.com
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        value: 947604684664-sbjfl0jmj332b81fmqeu7dd3tsct94l2.apps.googleusercontent.com
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: yz20bqni
        sync: false
      - key: CLOUDINARY_API_KEY
        value: 358381591648362
        sync: false
      - key: CLOUDINARY_API_SECRET
        value: KyZ6wf7pbZnI7qit0IH0mNX0Fr4
        sync: false
      # TURN / WebRTC (optional)
      - key: TURN_SERVER_URL
        sync: false
      - key: TURN_USERNAME
        sync: false
      - key: TURN_CREDENTIAL
        sync: false
